# Generated by Django 2.2.14 on 2020-07-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('database_path', models.CharField(max_length=255)),
                ('path1', models.CharField(max_length=255)),
                ('path2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSensing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=12)),
                ('lng', models.CharField(max_length=12)),
                ('feature', models.TextField()),
                ('filename', models.TextField()),
            ],
        ),
    ]
