CXX          = g++ -std=c++11
LIBS         = -l../build/librsearch.so
PYTHONCFLAGS = -I/usr/include/python3.5
SWIG         = swig
SHAREDFLAGS  = -shared
PYTHON       = python3
NUMPY_INCLUDE = /usr/local/lib/python3.5/dist-packages/numpy/core/include

